[package]
name = "eucommia-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.3"
jni = "0.21.1"
